### Signup (Register new user)
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "name": "Muhammad Naveed",
  "email": "muhammadnaveedcis@gmail.com",
  "password": "Password123"
}

###

### Login (Authenticate user)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "muhammadnaveedcis@gmail.com",
  "password": "naveed9039"
}

###

### Verify Email
POST http://localhost:3000/api/auth/verify
Content-Type: application/json

{
  "token": ""
}

###

### Get current user (with access token from login)
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWR5ZXZzMDIwMDAwMTIzdXA5MW5ocDBxIiwiZW1haWwiOiJtdWhhbW1hZG5hdmVlZGNpc0BnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1NDU1ODMwNiwiZXhwIjoxNzU0NTU5MjA2fQ.i8aO0LoXmUyOfARK7sqL47WJdpwTi6NYmSpbSIiKOjc

###

### Request Password Reset
POST http://localhost:3000/api/auth/request-password-reset
Content-Type: application/json

{
  "email": "muhammadnaveedcis@gmail.com"
}

###

### Reset Password
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "token": "PASTE_RESET_TOKEN_HERE",
  "newPassword": "NewPassword123"
}

###

### Refresh Token (cookie must be set automatically)
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json
Cookie: refreshToken=PASTE_REFRESH_TOKEN_HERE

###

### Logout
POST http://localhost:3000/api/auth/logout

###